@startuml 2
actor Child
participant "LoginSystem" as LS
participant "ChildrenList" as CL

Child -> LS: enter(lastname, firstname)
LS -> CL: searchChild()
CL --> LS: childFound / notFound
LS -> Child: success OR error message
@enduml
