@startuml 1
title NATUR BUCKS Volleyball Club - Admin Use Case Diagram

skinparam shadowing true
skinparam actorStyle awesome
skinparam usecase {
    BackgroundColor #F2F2F2
    BorderColor #444444
}
left to right direction

actor Admin <<Manager>>

usecase "UC01: Admin Login" as UC01
usecase "UC03: Register Child" as UC03
usecase "UC04: Delete Child" as UC04
usecase "UC05: Search Child" as UC05
usecase "UC06: View All Children" as UC06

usecase "UC07: Create Schedule" as UC07
usecase "UC08: Update Schedule" as UC08
usecase "UC09: View All Schedules" as UC09

usecase "UC10: Register Payment" as UC10
usecase "UC11: View Payment History" as UC11
usecase "UC12: View Unpaid Children" as UC12

Admin --> UC01
Admin --> UC03
Admin --> UC04
Admin --> UC05
Admin --> UC06
Admin --> UC07
Admin --> UC08
Admin --> UC09
Admin --> UC10
Admin --> UC11
Admin --> UC12

@enduml
